#!/usr/bin/env bash
# tools/build-color-gate.sh - Source-of-truth for the inline color-gate
# heredoc that is embedded in linuxinstall.sh, lib/updater.sh, restore_ssh.sh,
# and DeepClean.sh for the curl|bash fallback path.
#
# Why this exists:
#   The 4 inline copies MUST be byte-identical (same logic) so that the
#   gate produces the same USE_COLOR regardless of which file is sourced.
#   Previously each copy was maintained by hand, which led to drift bugs
#   (e.g. one copy forgot the TERM=dumb check).
#
# Two outputs:
#   1. STDOUT: the 4 heredoc blocks (one per consumer) for pasting.
#   2. STDERR: a hash file mapping consumer -> sha256 of the gate body,
#      for verify_sync.sh to detect drift.
#
# Usage: bash tools/build-color-gate.sh
#   - Paste STDOUT into each consumer between BEGIN_INHERIT_COLOR_GATE
#     and END_INHERIT_COLOR_GATE markers.
#   - verify_sync.sh runs `bash tools/build-color-gate.sh 2> /tmp/hashes`
#     and compares /tmp/hashes to the hashes of the live inline blocks.
set -eu

# Canonical gate function body.  Reads env vars and prints 0 or 1.
# The function name is parameterized by the caller; the BODY is shared.
# Use a single-quoted heredoc to prevent variable expansion, then sed
# to substitute the function name into the FN_NAME placeholder.
emit_gate_body() {
  local fn_name="$1"
  sed "s/__FN_NAME__/${fn_name}/g" <<'GATE_BODY'
  # Canonical ANSI gate.  Generated by tools/build-color-gate.sh;
  # DO NOT EDIT BY HAND.  See lib/color-gate.sh for the canonical version.
  __FN_NAME__() {
    if [ "${NEOHIRO_COLOR:-}" = "1" ]; then echo 1; return 0; fi
    if [ "${NEOHIRO_COLOR:-}" = "0" ]; then echo 0; return 0; fi
    if [ "${FORCE_TTY:-}" != "1" ] && [ ! -t 1 ]; then echo 0; return 0; fi
    if [ -n "${NO_COLOR:-}" ] && [ "${NO_COLOR:-}" != "0" ]; then echo 0; return 0; fi
    if [ "${TERM:-}" = "dumb" ]; then echo 0; return 0; fi
    if ! command -v tput >/dev/null 2>&1; then echo 0; return 0; fi
    local _tcol; _tcol=$(tput colors 2>/dev/null) || _tcol=""
    case "${_tcol}" in
      ''|*[!0-9]*) echo 0; return 0 ;;
      *) [ "${_tcol}" -ge 8 ] 2>/dev/null && echo 1 || echo 0; return 0 ;;
    esac
  }
GATE_BODY
}

# Emit the full block (with marker comments) for one consumer.
emit_block() {
  local fn_name="$1"
  local consumer="$2"
  echo "# BEGIN_INHERIT_COLOR_GATE (consumer=$consumer, fn=$fn_name)"
  echo "# This block is generated by tools/build-color-gate.sh."
  echo "# To regenerate: bash tools/build-color-gate.sh > /tmp/gate.sh"
  emit_gate_body "$fn_name"
  echo "# END_INHERIT_COLOR_GATE"
}

# Deterministic order so consumers can paste by name.
emit_block "_apply_color_gate"     "linuxinstall.sh"
emit_block "_updater_apply_gate"   "lib/updater.sh"
emit_block "_color_safe"           "restore_ssh.sh"
emit_block "_deepclean_apply_gate" "DeepClean.sh"

# Emit hash file (one per consumer) for drift detection.
{
  echo "# AUTO-GENERATED by tools/build-color-gate.sh - do not edit by hand."
  echo "# Format: <consumer>=<sha256 of gate body lines>"
  for c in linuxinstall.sh lib/updater.sh restore_ssh.sh DeepClean.sh; do
    # Re-emit to capture same content; hash the function body.
    block="$(emit_block "_fn" "$c")"
    hash="$(printf '%s\n' "$block" \
            | sed -n '/^  # Canonical ANSI gate/,/^  }$/p' \
            | sha256sum | cut -d' ' -f1)"
    echo "${c}=${hash}"
  done
} >&2
