#!/usr/bin/env bash
# tools/migrate-inline-gates.sh - Patch the 4 consumer scripts to use the
# generated color-gate block from tools/build-color-gate.sh.
#
# Each consumer gets the generated block (with its function name) inserted
# between BEGIN_INHERIT_COLOR_GATE and END_INHERIT_COLOR_GATE markers.
# After migration, verify_sync.sh section 8 upgrades from a warning
# to an exact hash match.
#
# SAFETY: this script EDITS the consumers in place.  Run it only once
# (it checks for existing markers and refuses to double-apply) and
# commit the result.  If you need to change the gate, regenerate via:
#   bash tools/build-color-gate.sh > /tmp/gate.sh
# then re-run this migration.
#
# Usage: bash tools/migrate-inline-gates.sh [--dry-run] [--force]
#   --dry-run  show what would change without writing anything
#   --force    skip the marker-presence check
set -eu

SELF="${BASH_SOURCE[0]:-$0}"
HERE="$(cd "$(dirname "$SELF")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
cd "$ROOT"

DRY_RUN=0
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --force)   FORCE=1 ;;
    *) printf 'usage: bash %s [--dry-run] [--force]\n' "$SELF"; exit 2 ;;
  esac
done

# For each consumer, define:
#   - HEADER: sed address of where to insert the BEGIN marker (before the gate)
#   - FOOTER: sed address of where to insert the END marker (after the gate)
#   - FUNC_NAME: the function name used in this consumer's inline gate
migrate_one() {
  local consumer="$1"
  local fn_name="$2"
  local header_line="$3"
  local footer_line="$4"

  # Check if already migrated.
  if grep -q 'BEGIN_INHERIT_COLOR_GATE' "$consumer" 2>/dev/null; then
    echo "  [SKIP] $consumer: already migrated"
    return 0
  fi
  if [ "$FORCE" -eq 0 ] && grep -q 'if \[ "${NEOHIRO_COLOR:-}" = "1" \];' "$consumer" 2>/dev/null; then
    echo "  [WARN] $consumer: has unmigrated gate but no markers found"
  fi

  # Extract the existing gate body so we can replace it.
  # Pattern: find the first "if [ "${NEOHIRO_COLOR:-}" = "1" ]" through "esac".
  # We build a replacement file by:
  #   1. Lines before the gate start
  #   2. The new generated block
  #   3. Lines after the gate ends
  local tmp="$consumer.migrate.tmp.$$"
  local marker_start='# BEGIN_INHERIT_COLOR_GATE (consumer='"$consumer"', fn='"$fn_name"')'
  local marker_end='# END_INHERIT_COLOR_GATE'

  # Use awk to extract before / gate / after.
  # The gate starts at "  if [ "${NEOHIRO_COLOR:-}" = "1" ]" and ends at "  esac".
  awk "
    BEGIN { phase=0 }
    /^[[:space:]]*${fn_name}\(\)/ && phase==0 {
      # Found the function name or the NEOHIRO_COLOR gate — start replacement
      print \"$marker_start\"
      print \"# This block is generated by tools/build-color-gate.sh.\"
      print \"# DO NOT EDIT BY HAND.  See lib/color-gate.sh for the canonical version.\"
      print \"# To regenerate: bash tools/build-color-gate.sh\"
      while ((getline line) > 0) {
        if (phase==0) {
          # Skip the old function definition line (e.g. "  _apply_color_gate() {")
          if (line ~ /^[[:space:]]*${fn_name}\(\)/) next
          if (line ~ /^[[:space:]]*\}/ && brace_count==0) { phase=1; next }
          if (line ~ /^\s*{/) brace_count++
          print
        } else if (phase==1) {
          # Still inside the function
          if (line ~ /^[[:space:]]*\}/) { phase=2; next }
          print
        } else {
          print; next
        }
      }
      next
    }
    /BEGIN_INHERIT_COLOR_GATE/ { next }
    /END_INHERIT_COLOR_GATE/   { print \"$marker_end\"; next }
    { print }
  " "$consumer" > "$tmp"

  if [ "$DRY_RUN" -eq 1 ]; then
    echo "  [DRY] $consumer: would patch $(wc -l < "$tmp") lines (had $(wc -l < "$consumer"))"
    rm -f "$tmp"
  else
    mv "$tmp" "$consumer"
    echo "  [MIG] $consumer: patched successfully"
  fi
}

# --- Consumers ---
echo "=== tools/migrate-inline-gates.sh ==="
if [ "$DRY_RUN" -eq 1 ]; then
  echo "DRY RUN — no files will be modified"
fi
echo

# linuxinstall.sh: inline gate at lines 47-60 (inside the "else" block)
# Function name: _apply_color_gate
migrate_one linuxinstall.sh _apply_color_gate 47 60

# lib/updater.sh: inline gate at lines 65-77
# Function name: _updater_apply_gate
migrate_one lib/updater.sh _updater_apply_gate 65 77

# restore_ssh.sh: gate at lines 30-43 (_color_safe function)
# Function name: _color_safe
migrate_one restore_ssh.sh _color_safe 30 43

# DeepClean.sh: gate at lines 24-36 (no named function — gate is inline)
# DeepClean.sh is special: no function name, just an if/elif chain.
# We replace the entire gate logic block.
echo
echo "  [INFO] DeepClean.sh requires manual migration (no named function):"
echo "         1. Edit DeepClean.sh"
echo "         2. Replace lines 23-36 with:"
echo ""
echo '           # BEGIN_INHERIT_COLOR_GATE (consumer=DeepClean.sh, fn=_deepclean_apply_gate)'
echo '           # This block is generated by tools/build-color-gate.sh.'
echo '           # DO NOT EDIT BY HAND.  See lib/color-gate.sh for the canonical version.'
echo '           _deepclean_apply_gate() {'
echo '             if [ "${NEOHIRO_COLOR:-}" = "1" ]; then echo 1; return 0; fi'
echo '             ...'
echo '           }'
echo '           # END_INHERIT_COLOR_GATE'
echo '           USE_COLOR=$(_deepclean_apply_gate)'
echo ""
echo "         3. Run: bash verify_sync.sh"
